import { link } from 'fs';
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const links=[{link:"/todos",label:"Todos"},{link:"/",label:"Home"},{link:"/docs",label:"Docs"}];


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <nav>
         <ul className='flex items-center'>
          {
            links.map((link)=>{
              return(
                <li key={link.link} className='px-4 text-2xl'>
                  <Link href={link.link}>{link.label}</Link>
                </li>
              )
            })
          }
        </ul>
      </nav>
      <div className={inter.className}>{children}</div>

 
    </html>
  )
}
